{
 "title": "Main dashboard 2",
 "time": { "from": "now-3m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "server",
    "query": "artillery-node, artillery_gunicorn"
   },
   {
    "name": "container",
    "query": "arq-soft-tp1_node_1, arq-soft-tp1_node_2, arq-soft-tp1_node_3, arq-soft-tp1_cadvisor_1, arq-soft-tp1_flask_1, arq-soft-tp1_grafana_1, arq-soft-tp1_graphite_1, arq-soft-tp1_gunicorn_1, arq-soft-tp1_nginx_1"
   }
  ]
 },
 "panels": [
  {
   "title": "Requests state (stacked)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(stats.gauges.$server.errors.*), 'Errored')"
    },
    {
     "target": "alias(stats.gauges.$server.requestsCompleted, 'Completed')"
    },
    {
     "target": "alias(stats.gauges.$server.pendingRequests, 'Pending')"
    }
   ]
  },
  {
   "title": "Response time (client-side)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "alias(stats.gauges.$server.scenarioDuration.max, 'Upper')"
    },
    {
     "target": "alias(stats.gauges.$server.scenarioDuration.median, 'Median')"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "alias(removeBelowValue(asPercent(derivative(keepLastValue(stats.gauges.cadvisor.-docker.cpu_cumulative_usage, 100)), 10000000000), 0.0001), 'docker')"
    },
    {
     "target": "alias(removeBelowValue(asPercent(derivative(keepLastValue(stats.gauges.cadvisor.arq-soft-tp1_node_1.cpu_cumulative_usage, 100)), 10000000000), 0.0001), 'node_1')"
    },
    {
     "target": "alias(removeBelowValue(asPercent(derivative(keepLastValue(stats.gauges.cadvisor.arq-soft-tp1_node_2.cpu_cumulative_usage, 100)), 10000000000), 0.0001), 'node_2')"
    },
    {
     "target": "alias(removeBelowValue(asPercent(derivative(keepLastValue(stats.gauges.cadvisor.arq-soft-tp1_node_3.cpu_cumulative_usage, 100)), 10000000000), 0.0001), 'node_3')"
    },
    {
     "target": "alias(removeBelowValue(asPercent(derivative(keepLastValue(stats.gauges.cadvisor.arq-soft-tp1_nginx_1.cpu_cumulative_usage, 100)), 10000000000), 0.0001), 'nginx')"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "alias(removeBelowValue(derivative(stats.gauges.cadvisor.arq-soft-tp1_nginx_1.rx_bytes), 0.0001), 'nginx_sent')"
    },
    {
     "target": "alias(removeBelowValue(derivative(stats.gauges.cadvisor.arq-soft-tp1_nginx_1.rx_bytes), 0.0001), 'nginx_recv')"
    },
    {
     "target": "alias(removeBelowValue(derivative(stats.gauges.cadvisor.arq-soft-tp1_gunicorn_1.tx_bytes), 0.0001), 'gunicron_sent')"
    },
    {
     "target": "alias(removeBelowValue(derivative(stats.gauges.cadvisor.arq-soft-tp1_gunicorn_1.rx_bytes), 0.0001), 'gunicorn_recv')"
    }
   ]
  }
 ]
}